/**
 * The design tokens from the user's mockup, ported verbatim.
 *
 * Every colour, radius, spacing step, family and size below is copied from the
 * `tailwind.config` block of `frontend_example.html` (lines 11-101). Treat that
 * file as the source of truth: change it there first, then mirror it here.
 */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#dbdad6',
        'on-background': '#1b1c1a',
        'on-primary-fixed': '#390c00',
        'surface-variant': '#e4e2de',
        secondary: '#506354',
        'on-surface': '#1b1c1a',
        'on-secondary-fixed-variant': '#394b3d',
        'surface-container': '#efeeea',
        'on-primary-fixed-variant': '#7d2c0d',
        'on-secondary-container': '#546758',
        'tertiary-fixed': '#90f2f7',
        'primary-fixed-dim': '#ffb59d',
        tertiary: '#00676a',
        'surface-container-high': '#eae8e4',
        'primary-fixed': '#ffdbd0',
        'surface-bright': '#fbf9f5',
        'inverse-surface': '#30312e',
        'on-tertiary-fixed-variant': '#004f52',
        'error-container': '#ffdad6',
        'tertiary-container': '#008286',
        error: '#ba1a1a',
        'secondary-fixed-dim': '#b7ccb9',
        primary: '#9a4121',
        'on-surface-variant': '#56423c',
        background: '#fbf9f5',
        surface: '#fbf9f5',
        'surface-container-lowest': '#ffffff',
        'inverse-primary': '#ffb59d',
        'on-tertiary-container': '#f3ffff',
        'secondary-fixed': '#d3e8d5',
        'on-tertiary-fixed': '#002021',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-primary': '#ffffff',
        'on-primary-container': '#fffbff',
        'tertiary-fixed-dim': '#73d6db',
        'surface-tint': '#9d4323',
        'secondary-container': '#d0e5d2',
        'inverse-on-surface': '#f2f0ed',
        outline: '#89726b',
        'on-error-container': '#93000a',
        'on-error': '#ffffff',
        'outline-variant': '#dcc1b8',
        'on-secondary-fixed': '#0e1f13',
        'surface-container-highest': '#e4e2de',
        'primary-container': '#b95836',
        'surface-container-low': '#f5f3ef',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-padding-desktop': '40px',
        base: '8px',
        'max-width-content': '720px',
        'inline-gap': '12px',
        'content-stack': '24px',
        'section-gap': '48px',
        'container-padding-mobile': '20px',
      },
      fontFamily: {
        'label-caps': ['Hanken Grotesk'],
        'display-lg-mobile': ['Literata'],
        'ui-main': ['Hanken Grotesk'],
        'headline-md': ['Literata'],
        'display-lg': ['Literata'],
        'helper-text': ['Hanken Grotesk'],
        'recipe-body': ['Literata'],
      },
      fontSize: {
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '38px', fontWeight: '700' }],
        'ui-main': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'helper-text': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'recipe-body': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
    },
  },
}
